"""Country styles + synthetic name/place pools for the synthetic-passport generator.

EVERYTHING HERE IS FICTIONAL TEST DATA.

- Emblems are deliberately *stylized geometric motifs*, NOT the official state
  emblems/arms of any country. The layout is the generic ICAO-9303 TD3 data-page
  format (an international standard, not any country's proprietary design).
- Name pools are common, generic given/surnames combined at random by seed; any
  resulting full name is fictional and not intended to identify a real person.
- Passport-number *formats* approximate the real structure (so OCR/regex parsing is
  exercised) but the values are synthetic.

The `pn_format` mini-DSL: 'A' = uppercase letter (no I/O/Q to avoid OCR ambiguity),
'#' = digit, 'N' = alphanumeric; any other char is literal.
"""

# Native scripts: dir "rtl" only for Urdu (Pakistan); raqm handles the shaping.
COUNTRIES = {
    "IND": {
        "display": "India", "nationality_long": "India",
        "native": "भारत गणराज्य", "native_font": "deva", "native_dir": "ltr",
        "country_en": "REPUBLIC OF INDIA",
        "passport_native": "पासपोर्ट", "passport_font": "deva",
        "header": "#10235e", "tint": "#eef2f8", "accent": "#ff9933",
        "country_color": "#ffffff",
        "emblem": "chakra", "emblem_color": "#ff9933",
        "authority": "Ministry of External Affairs",
        "pn_format": "A#######",
        "places": ["MUMBAI", "DELHI", "BENGALURU", "HYDERABAD", "CHENNAI", "PUNE", "KOLKATA", "AHMEDABAD"],
        "surnames": ["KUMAR", "SHARMA", "PATEL", "SINGH", "REDDY", "GUPTA", "NAIR", "RAO"],
        "given_m": ["ARJUN", "ROHAN", "VIKRAM", "ANIL", "RAHUL", "KARTHIK"],
        "given_f": ["PRIYA", "ANITA", "DIVYA", "MEERA", "SNEHA", "POOJA"],
    },
    "CHN": {
        "display": "China", "nationality_long": "China",
        "native": "中华人民共和国", "native_font": "cjk_sc", "native_dir": "ltr",
        "country_en": "PEOPLE'S REPUBLIC OF CHINA",
        "passport_native": "护照", "passport_font": "cjk_sc",
        "header": "#c8102e", "tint": "#f7eeee", "accent": "#ffd200",
        "country_color": "#ffd200",
        "emblem": "stars", "emblem_color": "#ffd200",
        "authority": "National Immigration Administration",
        "pn_format": "E########",
        "places": ["BEIJING", "SHANGHAI", "GUANGDONG", "SICHUAN", "ZHEJIANG", "JIANGSU", "FUJIAN"],
        "surnames": ["WANG", "LI", "ZHANG", "LIU", "CHEN", "YANG", "ZHAO", "HUANG"],
        "given_m": ["WEI", "HAO", "JUN", "MING", "LEI", "FENG"],
        "given_f": ["YAN", "LING", "MEI", "FANG", "JING", "NA"],
    },
    "CAN": {
        "display": "Canada", "nationality_long": "Canada",
        "native": "CANADA", "native_font": "sansb", "native_dir": "ltr",
        "country_en": "CANADA",
        "passport_native": "PASSEPORT", "passport_font": "sansb",
        "header": "#a6192e", "tint": "#f6ecec", "accent": "#a6192e",
        "country_color": "#ffffff",
        "emblem": "maple", "emblem_color": "#ffffff",
        "authority": "Immigration, Refugees and Citizenship",
        "pn_format": "AA######",
        "places": ["TORONTO", "VANCOUVER", "MONTREAL", "CALGARY", "OTTAWA", "EDMONTON", "WINNIPEG"],
        "surnames": ["TREMBLAY", "ROY", "GAGNON", "SMITH", "BROWN", "WILSON", "MARTIN", "LEE"],
        "given_m": ["LIAM", "NOAH", "WILLIAM", "ETHAN", "LUCAS", "JACOB"],
        "given_f": ["EMMA", "OLIVIA", "SOPHIA", "CHLOE", "AVA", "EMILY"],
    },
    "KOR": {
        "display": "South Korea", "nationality_long": "Republic of Korea",
        "native": "대한민국", "native_font": "cjk_kr", "native_dir": "ltr",
        "country_en": "REPUBLIC OF KOREA",
        "passport_native": "여권", "passport_font": "cjk_kr",
        "header": "#003478", "tint": "#eaeff6", "accent": "#c60c30",
        "country_color": "#ffffff",
        "emblem": "taegeuk", "emblem_color": "#c60c30",
        "authority": "Ministry of Foreign Affairs",
        "pn_format": "M########",
        "places": ["SEOUL", "BUSAN", "INCHEON", "DAEGU", "DAEJEON", "GWANGJU", "ULSAN"],
        "surnames": ["KIM", "LEE", "PARK", "CHOI", "JUNG", "KANG", "CHO", "YOON"],
        "given_m": ["MINJUN", "SEOJUN", "DOYUN", "JIHO", "HAJUN", "EUNWOO"],
        "given_f": ["SEOYEON", "JIWOO", "SEOYUN", "JIYU", "HAEUN", "YUNA"],
    },
    "PHL": {
        "display": "Philippines", "nationality_long": "Philippines",
        "native": "REPUBLIKA NG PILIPINAS", "native_font": "sansb", "native_dir": "ltr",
        "country_en": "REPUBLIC OF THE PHILIPPINES",
        "passport_native": "PASAPORTE", "passport_font": "sansb",
        "header": "#0038a8", "tint": "#eaeef8", "accent": "#fcd116",
        "country_color": "#ffffff",
        "emblem": "sun", "emblem_color": "#fcd116",
        "authority": "Department of Foreign Affairs",
        "pn_format": "P#######A",
        "places": ["MANILA", "QUEZON CITY", "CEBU", "DAVAO", "MAKATI", "TAGUIG", "PASIG"],
        "surnames": ["SANTOS", "REYES", "CRUZ", "BAUTISTA", "GARCIA", "MENDOZA", "TORRES", "RAMOS"],
        "given_m": ["JOSE", "ANGELO", "MARK", "PAOLO", "MIGUEL", "CARLO"],
        "given_f": ["MARIA", "ANGELICA", "GRACE", "JOY", "ANNA", "ROSE"],
    },
    "TWN": {
        "display": "Taiwan", "nationality_long": "Republic of China (Taiwan)",
        "native": "中華民國", "native_font": "cjk_tc", "native_dir": "ltr",
        "country_en": "REPUBLIC OF CHINA (TAIWAN)",
        "passport_native": "護照", "passport_font": "cjk_tc",
        "header": "#000095", "tint": "#e9eaf6", "accent": "#fe0000",
        "country_color": "#ffffff",
        "emblem": "sunburst", "emblem_color": "#ffffff",
        "authority": "Bureau of Consular Affairs, MOFA",
        "pn_format": "#########",
        "places": ["TAIPEI", "NEW TAIPEI", "TAICHUNG", "KAOHSIUNG", "TAINAN", "TAOYUAN", "HSINCHU"],
        "surnames": ["CHEN", "LIN", "HUANG", "CHANG", "LI", "WANG", "WU", "LIU"],
        "given_m": ["CHIA-HAO", "YU-TING", "CHENG", "WEI-TING", "PO-YU", "CHIH-WEI"],
        "given_f": ["YU-HSUAN", "HSIN-YI", "PEI-YU", "YA-TING", "MENG-CHEN", "SHU-FEN"],
    },
    "MEX": {
        "display": "Mexico", "nationality_long": "Mexico",
        "native": "ESTADOS UNIDOS MEXICANOS", "native_font": "sansb", "native_dir": "ltr",
        "country_en": "UNITED MEXICAN STATES",
        "passport_native": "PASAPORTE", "passport_font": "sansb",
        "header": "#006847", "tint": "#eaf3ee", "accent": "#ce1126",
        "country_color": "#ffffff",
        "emblem": "seal", "emblem_color": "#ce1126",
        "authority": "Secretaría de Relaciones Exteriores",
        "pn_format": "G########",
        "places": ["CIUDAD DE MEXICO", "GUADALAJARA", "MONTERREY", "PUEBLA", "TIJUANA", "LEON", "QUERETARO"],
        "surnames": ["GARCIA", "HERNANDEZ", "MARTINEZ", "LOPEZ", "GONZALEZ", "PEREZ", "RAMIREZ", "FLORES"],
        "given_m": ["JOSE", "JUAN", "LUIS", "CARLOS", "MIGUEL", "JORGE"],
        "given_f": ["MARIA", "GUADALUPE", "ABIGAIL", "SOFIA", "VALERIA", "XIMENA"],
    },
    "BRA": {
        "display": "Brazil", "nationality_long": "Brazil",
        "native": "REPÚBLICA FEDERATIVA DO BRASIL", "native_font": "sansb", "native_dir": "ltr",
        "country_en": "FEDERATIVE REPUBLIC OF BRAZIL",
        "passport_native": "PASSAPORTE", "passport_font": "sansb",
        "header": "#009c3b", "tint": "#eaf4ec", "accent": "#ffdf00",
        "country_color": "#ffdf00",
        "emblem": "globe", "emblem_color": "#ffdf00",
        "authority": "Polícia Federal",
        "pn_format": "AA######",
        "places": ["SAO PAULO", "RIO DE JANEIRO", "BRASILIA", "SALVADOR", "FORTALEZA", "BELO HORIZONTE", "CURITIBA"],
        "surnames": ["SILVA", "SANTOS", "OLIVEIRA", "SOUZA", "LIMA", "PEREIRA", "FERREIRA", "COSTA"],
        "given_m": ["JOAO", "PEDRO", "LUCAS", "GABRIEL", "RAFAEL", "BRUNO"],
        "given_f": ["ANA", "BEATRIZ", "JULIA", "MARIANA", "LARISSA", "CAMILA"],
    },
    "GBR": {
        "display": "United Kingdom", "nationality_long": "British Citizen",
        "native": "UNITED KINGDOM OF GREAT BRITAIN", "native_font": "sansb", "native_dir": "ltr",
        "country_en": "AND NORTHERN IRELAND",
        "passport_native": "PASSPORT", "passport_font": "sansb",
        "header": "#7a1f2b", "tint": "#f1eaeb", "accent": "#c8a951",
        "country_color": "#e8c97a",
        "emblem": "shield", "emblem_color": "#c8a951",
        "authority": "His Majesty's Passport Office",
        "pn_format": "#########",
        "places": ["LONDON", "MANCHESTER", "BIRMINGHAM", "GLASGOW", "LEEDS", "LIVERPOOL", "BRISTOL"],
        "surnames": ["SMITH", "JONES", "TAYLOR", "BROWN", "WILLIAMS", "WILSON", "EVANS", "THOMAS"],
        "given_m": ["OLIVER", "GEORGE", "HARRY", "JACK", "CHARLIE", "THOMAS"],
        "given_f": ["OLIVIA", "AMELIA", "ISLA", "AVA", "GRACE", "FREYA"],
    },
    "PAK": {
        "display": "Pakistan", "nationality_long": "Pakistan",
        "native": "اسلامی جمہوریہ پاکستان", "native_font": "arabic", "native_dir": "rtl",
        "country_en": "ISLAMIC REPUBLIC OF PAKISTAN",
        "passport_native": "پاسپورٹ", "passport_font": "arabic",
        "header": "#01411c", "tint": "#e8f1ea", "accent": "#ffffff",
        "country_color": "#ffffff",
        "emblem": "crescent", "emblem_color": "#ffffff",
        "authority": "Directorate General of Immigration & Passports",
        "pn_format": "AA#######",
        "places": ["KARACHI", "LAHORE", "ISLAMABAD", "RAWALPINDI", "FAISALABAD", "MULTAN", "PESHAWAR"],
        "surnames": ["KHAN", "AHMED", "ALI", "HUSSAIN", "MALIK", "SHEIKH", "QURESHI", "BUTT"],
        "given_m": ["MUHAMMAD", "AHMED", "BILAL", "USMAN", "HAMZA", "FARHAN"],
        "given_f": ["AYESHA", "FATIMA", "ZAINAB", "SANA", "HIRA", "MARYAM"],
    },
}

# Stable display order = the chosen H-1B-weighted set order.
ORDER = ["IND", "CHN", "CAN", "KOR", "PHL", "TWN", "MEX", "BRA", "GBR", "PAK"]
